# Generated by Django 5.2.1 on 2025-05-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_organization_name_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('responder', 'Responder'), ('manager', 'Manager')], default='viewer', max_length=10),
        ),
    ]
